# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec9558b34f721ff39b8709027f8ea7a161a4209bb4c615a2bfc403685edbce01b05fbd1301ac94f02ae802f93d20e421742684a95b372b4f3cc4c1ccf78061ed

test:
  secret_key_base: b9f0283f7c96be115f8a7a91680dddc14bb77b4de43295b845cab9120462491e3ea5a7780df3f8b395835675336cee06dd0329417d9b69ead7dc954d0ba29e67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
